// =============================================================================
//  takeoff/csv-feed.js (CommonJS) — AI rows → BOM import CSV + gap verify list.
//  Mirrors the spike's railway/csv-feed.js. The platform's "Import BOM
//  Spreadsheet" workflow does all resolution; this just emits the exact CSV.
//  Columns (0-indexed): 0 Tag · 1 Component · 2 Drawing · 3 Form Type ·
//  4 Mat Type · 5 Spec · 6 Material · 7 QTY · 8 FT(L) · 9 INCH(L) · 10 FT(W) ·
//  11 INCH(W) · 12 Galv · 13 Surface Area · 14 Confidence.
// =============================================================================

const HEADER_LINES = [
  "MATERIAL COMPASS - BOM Import Template (AI Take-off)",
  "Generated by AI Take-off - review in BOM Staging",
  "Tag,Component,Drawing Number,Form Type,Mat Type,Specification,Material,QTY,FT(L),INCH(L),FT(W),INCH(W),Galv,Surface Area,Confidence",
  "blue = lookup (must match Creator) ; green = direct entry ; * = required",
  "",
  "",
];

// Strip anything that would break the naive comma-split / line-split.
function cell(v) { return String(v == null ? "" : v).replace(/[,\r\n]+/g, " ").trim(); }
// confidence 0–1 → integer percent string ("" if missing).
function pct(c) { const n = Number(c); return Number.isFinite(n) ? String(Math.round(n * 100)) : ""; }

// Unwrap the occasional JSON-encoded-string `rows` (forced-tool-use quirk) → real array.
function normalizeRows(rows) {
  if (typeof rows === "string") { try { rows = JSON.parse(rows); } catch (e) { rows = []; } }
  return Array.isArray(rows) ? rows : [];
}

const isQuantified = function (r) { return (Number(r.quantity) || 0) > 0; };

// WHAT GETS ORDERED. `quantity` is per ONE unit of the component (that's what the drawing shows);
// `quantity_total` is that times how many of the component the job builds. The BOM must carry the
// TOTAL: the project's own Deluge divides BOM sums by Component.Quantity to get per-unit cost, so a
// per-unit BOM would under-order the steel AND under-report every unit cost. Falls back to
// `quantity` when nothing multiplied it (single-unit components, or an older caller).
function orderQty(r) {
  const total = Number(r.quantity_total);
  return Number.isFinite(total) && total > 0 ? total : (Number(r.quantity) || 0);
}

function splitFt(n) {
  const raw = Number(n) || 0;
  const ft = Math.max(0, Math.floor(raw));
  const inch = Math.round((raw - ft) * 12);
  return inch >= 12 ? [ft + 1, 0] : [ft, inch];  // carry: INCH lookup only holds 0–<12"
}

function buildImportCsv(rows) {
  rows = normalizeRows(rows).filter(isQuantified); // only quantified rows reach the BOM CSV
  const lines = HEADER_LINES.slice();
  rows.forEach(function (r, i) {
    const ftPair = splitFt(r.length_ft);
    const wPair = splitFt(r.width_ft); // Plate/Sheet/Tread Plate width (else 0/0)
    const tag = cell(r.member_mark) || "AI-" + String(i + 1).padStart(3, "0");
    lines.push([
      tag,                       // 0  Tag
      cell(r.component),         // 1  Component
      cell(r.source_sheet),      // 2  Drawing Number
      cell(r.form_type),         // 3  Form Type
      cell(r.material_type),     // 4  Mat Type
      cell(r.specification),     // 5  Specification
      cell(r.size),              // 6  Material
      cell(orderQty(r)),         // 7  QTY — the JOB total (per unit × units built)
      cell(ftPair[0]),           // 8  FT(L)   — dimensions are 0 when empty, never blank
      cell(ftPair[1]),           // 9  INCH(L)
      cell(wPair[0]),            // 10 FT(W)
      cell(wPair[1]),            // 11 INCH(W)
      r.galvanized ? "Yes" : "", // 12 Galv
      "",                        // 13 Surface Area
      pct(r.confidence),         // 14 Confidence %
    ].join(","));
  });
  return lines.join("\n");
}

const VERIFY_HEADER = [
  "MATERIAL COMPASS - AI Take-off: ITEMS TO VERIFY & QUANTIFY",
  "These were identified on the drawings but could not be counted/sized from this set.",
  "Confirm QTY (and Material if blank) from civil/arch/spec, then add to the BOM.",
  "Drawing,Form Type,Mat Type,Specification,Material,Confidence,Why / Note",
];

function buildVerifyList(rows) {
  rows = normalizeRows(rows).filter(function (r) { return !isQuantified(r); }); // gap rows
  const lines = VERIFY_HEADER.slice();
  rows.forEach(function (r) {
    lines.push([
      cell(r.source_sheet),
      cell(r.form_type),
      cell(r.material_type),
      cell(r.specification),
      cell(r.size),
      pct(r.confidence),
      cell(r.note),
    ].join(","));
  });
  return lines.join("\n");
}

module.exports = { buildImportCsv, buildVerifyList };
